#!/usr/bin/env python3
"""Better conflict analysis - only real conflicts"""

# Real conflicts (same team name, different codes)
real_conflicts = [
    ('BALL STATE', 'BSU', 'BALL'),
    ('CAMPBELL', 'CAMP', 'CAM'),
    ('INCARNATE WORD', 'IW', 'UIW'),
    ('MCNEESE', 'MCNS', 'MCN'),
    ('QUEENS', 'QU', 'QUOC'),
    ('UMASS LOWELL', 'MASSL', 'UML'),
    ('WILLIAM & MARY', 'WM', 'W&M'),
    ('BETHUNE-COOKMAN', 'COOK', 'BCU'),
    ('STONEHILL', 'STNH', 'STO'),
    ('LE MOYNE', 'LMC', 'LEM'),
]

# Teams from Grok that are safe to add (no conflicts with our mappings)
safe_to_add = [
    ('ABILENE CHRISTIAN', 'ACU'),
    ('AKRON', 'AKR'),
    ('ALBANY', 'ALB'),
    ('ALABAMA STATE', 'ALST'),
    ('AMERICAN', 'AMER'),
    ('APPALACHIAN STATE', 'APP'),
    ('ARKANSAS - PINE BLUFF', 'UAPB'),
    ('ARKANSAS STATE', 'ARST'),
    ('AUSTIN PEAY', 'APSU'),
    ('BAYLOR', 'BAY'),
    ('BINGHAMTON', 'BING'),
    ('BOSTON COLLEGE', 'BC'),
    ('BOSTON UNIVERSITY', 'BU'),
    ('BOWLING GREEN', 'BGSU'),
    ('BROWN', 'BRWN'),
    ('BRYANT', 'BRY'),
    ('BUCKNELL', 'BUCK'),
    ('CAL POLY', 'CP'),
    ('CALIFORNIA', 'CAL'),
    ('CALIFORNIA BAPTIST', 'CBU'),
    ('CANISIUS', 'CAN'),
    ('CHARLESTON', 'COFC'),
    ('CHARLOTTE', 'CLT'),
    ('CHATTANOOGA', 'UTC'),
    ('CHICAGO STATE', 'CHST'),
    ('CLEVELAND STATE', 'CLEV'),
    ('COASTAL CAROLINA', 'CCU'),
    ('COLGATE', 'COLG'),
    ('COLUMBIA', 'COLU'),
    ('COPPIN STATE', 'COPP'),
    ('CORNELL', 'COR'),
    ('CSU BAKERSFIELD', 'CSUB'),
    ('CSU FULLERTON', 'CSUF'),
    ('CSU NORTHRIDGE', 'CSUN'),
    ('DARTMOUTH', 'DART'),
    ('DAYTON', 'DAY'),
    ('DELAWARE', 'DEL'),
    ('DELAWARE STATE', 'DSU'),
    ('DENVER', 'DEN'),
    ('DETROIT MERCY', 'DETM'),
    ('DREXEL', 'DREX'),
    ('DUQUESNE', 'DUQ'),
    ('EAST TENNESSEE STATE', 'ETSU'),
    ('ELON', 'ELON'),
    ('FLORIDA', 'FLA'),
    ('FLORIDA A&M', 'FAMU'),
    ('FLORIDA GULF COAST', 'FGCU'),
    ('FLORIDA INTERNATIONAL', 'FIU'),
    ('FORDHAM', 'FOR'),
    ('FURMAN', 'FUR'),
    ('GARDNER-WEBB', 'GWEB'),
    ('GEORGE MASON', 'GMU'),
    ('GEORGE WASHINGTON', 'GW'),
    ('GREEN BAY', 'GB'),
    ('HAMPTON', 'HAMP'),
    ('HARVARD', 'HARV'),
    ('HAWAII', 'HAW'),
    ('HIGH POINT', 'HPU'),
    ('HOUSTON CHRISTIAN', 'HCU'),
    ('HOWARD', 'HOW'),
    ('INDIANA', 'IU'),
    ('IONA', 'IONA'),
    ('IU INDY', 'IUIN'),
    ('JACKSONVILLE', 'JAX'),
    ('JACKSONVILLE STATE', 'JVST'),
    ('JAMES MADISON', 'JMU'),
    ('KANSAS CITY', 'KC'),
    ('KENNESAW STATE', 'KENN'),
    ('KENT STATE', 'KENT'),
    ('LAFAYETTE', 'LAF'),
    ('LAMAR', 'LAM'),
    ('LEHIGH', 'LEH'),
    ('LIBERTY', 'LIB'),
    ('LONG BEACH STATE', 'LBSU'),
    ('LONGWOOD', 'LONG'),
    ('LOUISIANA', 'UL'),
    ('LOYOLA MARYLAND', 'L-MD'),
    ('MARIST', 'MRST'),
    ('MARSHALL', 'MRSH'),
    ('MASSACHUSETTS', 'MASS'),
    ('MERCER', 'MER'),
    ('MERCYHURST', 'MERC'),
    ('MERRIMACK', 'MRMK'),
    ('MIAMI OF OHIO', 'M-OH'),
    ('MIDDLE TENNESSEE', 'MTSU'),
    ('MILWAUKEE', 'MILW'),
    ('MISSISSIPPI VALLEY STATE', 'MVSU'),
    ('MISSOURI', 'MIZ'),
    ('MISSOURI STATE', 'MOST'),
    ('MOREHEAD STATE', 'MORE'),
    ('MORGAN STATE', 'MORG'),
    ('NAVY', 'NAVY'),
    ('NC STATE', 'NCSU'),
    ('NEW HAMPSHIRE', 'UNH'),
    ('NEW MEXICO', 'UNM'),
    ('NEW MEXICO STATE', 'NMSU'),
    ('NIAGARA', 'NIAG'),
    ('NJIT', 'NJIT'),
    ('NORFOLK STATE', 'NORF'),
    ('NORTH CAROLINA A&T', 'NCAT'),
    ('NORTH CAROLINA CENTRAL', 'NCCU'),
    ('NORTHWESTERN', 'NU'),
    ('OAKLAND', 'OAK'),
    ('OKLAHOMA', 'OU'),
    ('OLE MISS', 'MISS'),
    ('OMAHA', 'OMA'),
    ('ORAL ROBERTS', 'ORU'),
    ('PACIFIC', 'PAC'),
    ('PENNSYLVANIA', 'PENN'),
    ('PEPPERDINE', 'PEPP'),
    ('PORTLAND', 'PORT'),
    ('PRAIRIE VIEW A&M', 'PV'),
    ('PRESBYTERIAN', 'PRES'),
    ('PRINCETON', 'PRIN'),
    ('RHODE ISLAND', 'URI'),
    ('RICE', 'RICE'),
    ('RICHMOND', 'RICH'),
    ('RIDER', 'RID'),
    ('SACRED HEART', 'SHU'),
    ('SAM HOUSTON', 'SHSU'),
    ('SAMFORD', 'SAM'),
    ('SAN DIEGO', 'USD'),
    ('SAN FRANCISCO', 'SF'),
    ('SAN JOSE STATE', 'SJSU'),
    ('SEATTLE', 'SEA'),
    ('SIENA', 'SIE'),
    ('SOUTH CAROLINA', 'SC'),
    ('SOUTH FLORIDA', 'USF'),
    ('ST. BONAVENTURE', 'SBU'),
    ('ST. FRANCIS', 'SFPA'),
    ('ST. PETER\'S', 'SPU'),
    ('ST. THOMAS', 'STMN'),
    ('STANFORD', 'STAN'),
    ('STONY BROOK', 'STBK'),
    ('SYRACUSE', 'SYR'),
    ('TARLETON', 'TAR'),
    ('TCU', 'TCU'),
    ('TENNESSEE STATE', 'TNST'),
    ('TENNESSEE TECH', 'TNTC'),
    ('TEXAS - ARLINGTON', 'UTA'),
    ('TEXAS SOUTHERN', 'TXSO'),
    ('TOWSON', 'TOW'),
    ('TROY', 'TROY'),
    ('TULANE', 'TULN'),
    ('UC DAVIS', 'UCD'),
    ('UC IRVINE', 'UCI'),
    ('UC RIVERSIDE', 'UCR'),
    ('UC SAN DIEGO', 'UCSD'),
    ('UC SANTA BARBARA', 'UCSB'),
    ('UMBC', 'UMBC'),
    ('UNC ASHEVILLE', 'UNCA'),
    ('UNC WILMINGTON', 'UNCW'),
    ('USC', 'USC'),
    ('USC UPSTATE', 'UPST'),
    ('UT RIO GRANDE VALLEY', 'RGV'),
    ('UTAH', 'UTAH'),
    ('UTAH TECH', 'UTU'),
    ('UTAH VALLEY', 'UVU'),
    ('VANDERBILT', 'VAN'),
    ('VCU', 'VCU'),
    ('VERMONT', 'UVM'),
    ('VMI', 'VMI'),
    ('WEST GEORGIA', 'WGA'),
    ('WEST VIRGINIA', 'WVU'),
    ('WINTHROP', 'WIN'),
    ('WOFFORD', 'WOF'),
    ('WRIGHT STATE', 'WRST'),
    ('WYOMING', 'WYO'),
    ('YALE', 'YALE'),
    ('YOUNGSTOWN STATE', 'YSU'),
]

print("=" * 80)
print("CONFLICT ANALYSIS")
print("=" * 80)
print(f"\n[!] REAL CONFLICTS (DO NOT CHANGE OURS - trust verified mappings): {len(real_conflicts)}")
for team, our_code, grok_code in real_conflicts:
    print(f"  {team:40} | OUR: {our_code:6} | GROK: {grok_code:6}")

print(f"\n[+] SAFE TO ADD (no conflicts): {len(safe_to_add)}")
print("\nFirst 20 teams to add:")
for team, code in safe_to_add[:20]:
    print(f"  {team:40} -> {code}")

print(f"\n... and {len(safe_to_add) - 20} more teams")
print("\n" + "=" * 80)
print("RECOMMENDATION:")
print("=" * 80)
print(f"[OK] SAFE TO ADD all {len(safe_to_add)} teams from 'safe_to_add' list")
print(f"[!] DO NOT CHANGE the {len(real_conflicts)} conflicting teams - keep our verified codes")
print("=" * 80)
