#!/usr/bin/env python3
"""Compare our mappings to Grok's list"""

# Our verified mappings (from kalshi_client.py)
our_mappings = {
    'NORTH CAROLINA STATE': 'NCST',
    'NORTH CAROLINA': 'UNC',
    'SOUTH CAROLINA STATE': 'SCST',
    'SOUTH CAROLINA': 'SCAR',
    'NORTH DAKOTA STATE': 'NDSU',
    'NORTH DAKOTA': 'UND',
    'SOUTH DAKOTA STATE': 'SDST',
    'SOUTH DAKOTA': 'SDAK',
    'TEXAS A&M': 'TXAM',
    'TEXAS TECH': 'TTU',
    'TEXAS STATE': 'TXST',
    'TEXAS': 'TEX',
    'ARIZONA STATE': 'ASU',
    'ARIZONA': 'ARIZ',
    'MICHIGAN STATE': 'MSU',
    'MICHIGAN': 'MICH',
    'OHIO STATE': 'OSU',
    'OHIO': 'OHIO',
    'OKLAHOMA STATE': 'OKST',
    'OKLAHOMA': 'OKLA',
    'IOWA STATE': 'ISU',
    'IOWA': 'IOWA',
    'KANSAS STATE': 'KSU',
    'KANSAS': 'KU',
    'INDIANA STATE': 'INST',
    'INDIANA': 'IND',
    'ILLINOIS STATE': 'ILST',
    'ILLINOIS': 'ILL',
    'MISSISSIPPI STATE': 'MSST',
    'MISSOURI STATE': 'MOSU',
    'MISSOURI': 'MIZZ',
    'FLORIDA STATE': 'FSU',
    'PENN STATE': 'PSU',
    'OREGON STATE': 'ORST',
    'OREGON': 'ORE',
    'WASHINGTON STATE': 'WSU',
    'WASHINGTON': 'WASH',
    'COLORADO STATE': 'CSU',
    'COLORADO': 'COLO',
    'UTAH STATE': 'USU',
    'UTAH': 'UTA',
    'IDAHO STATE': 'IDST',
    'IDAHO': 'IDHO',
    'PORTLAND STATE': 'PRST',
    'MONTANA STATE': 'MTST',
    'MONTANA': 'MONT',
    'NORTHERN ARIZONA': 'NAU',
    'NORTHERN COLORADO': 'UNCO',
    'NORTHERN ILLINOIS': 'NIU',
    'NORTHERN IOWA': 'UNI',
    'NORTHERN KENTUCKY': 'NKU',
    'NORTHWESTERN STATE': 'NWST',
    'NORTHWESTERN': 'NW',
    'STEPHEN F. AUSTIN': 'SFA',
    'NICHOL': 'NICH',
    'NICHOLLS': 'NICH',
    'SOUTHERN CALIFORNIA': 'USC',
    'SOUTHERN ILLINOIS': 'SIU',
    'SOUTHERN INDIANA': 'USI',
    'SOUTHERN MISS': 'USM',
    'SOUTHERN UTAH': 'SUU',
    'SOUTHEAST MISSOURI STATE': 'SEMO',
    'SOUTHEASTERN LOUISIANA': 'SELA',
    'EASTERN KENTUCKY': 'EKU',
    'EASTERN MICHIGAN': 'EMU',
    'EASTERN ILLINOIS': 'EIU',
    'EASTERN WASHINGTON': 'EWU',
    'WESTERN KENTUCKY': 'WKU',
    'WESTERN MICHIGAN': 'WMU',
    'WESTERN ILLINOIS': 'WIU',
    'WESTERN CAROLINA': 'WCU',
    'CENTRAL MICHIGAN': 'CMU',
    'CENTRAL CONNECTICUT STATE': 'CCSU',
    'CENTRAL ARKANSAS': 'CARK',
    'LOUISIANA STATE': 'LSU',
    'LOUISIANA TECH': 'LT',
    'LOUISIANA-MONROE': 'ULM',
    'LOUISIANA': 'ULL',
    'LSU': 'LSU',
    'GEORGETOWN': 'GTWN',
    'HOLY CROSS': 'HC',
    'STONEHILL': 'STNH',
    'LE MOYNE': 'LMC',
    'SETON HALL': 'HALL',
    'MARQUETTE': 'MARQ',
    'WAGNER': 'WAG',
    'FAIRLEIGH DICKINSON': 'FDU',
    'DUKE': 'DUKE',
    'VIRGINIA TECH': 'VT',
    'GEORGIA': 'UGA',
    'GEORGIA STATE': 'GAST',
    'GEORGIA SOUTHERN': 'GASO',
    'GEORGIA TECH': 'GT',
    'ARMY': 'ARMY',
    'ROBERT MORRIS': 'RMU',
    'PURDUE FORT WAYNE': 'PFW',
    'WILLIAM & MARY': 'WM',
    'CAMPBELL': 'CAMP',
    'WAKE FOREST': 'WAKE',
    'BALL STATE': 'BSU',
    'TOLEDO': 'TOL',
    'UNC GREENSBORO': 'UNCG',
    'THE CITADEL': 'CIT',
    'CITADEL': 'CIT',
    'SAN DIEGO STATE': 'SDSU',
    'SMU': 'SMU',
    'SOUTHERN METHODIST': 'SMU',
    'LOUISVILLE': 'LOU',
    'NORTH ALABAMA': 'UNA',
    'STETSON': 'STET',
    'RADFORD': 'RAD',
    'PRESBYTERIAN': 'PRE',
    'LIPSCOMB': 'LIP',
    'NORTH FLORIDA': 'UNF',
    'UMASS LOWELL': 'MASSL',
    'MAINE': 'ME',
    'CHARLESTON SOUTHERN': 'CHSO',
    'NORTHEASTERN': 'NE',
    'DEPAUL': 'DEP',
    'XAVIER': 'XAV',
    'LONG ISLAND': 'LIU',
    'SAINT JOSEPH': 'JOES',
    'ST JOSEPH': 'JOES',
    "ST. JOSEPH'S": 'JOES',
    'LA SALLE': 'LAS',
    'HOFSTRA': 'HOF',
    'MONMOUTH': 'MONM',
    'BUFFALO': 'BUFF',
    'OLD DOMINION': 'ODU',
    'QUEENS': 'QU',
    'BELLARMINE': 'BELL',
    "MOUNT ST. MARY'S": 'MSM',
    'MANHATTAN': 'MAN',
    'FAIRFIELD': 'FAIR',
    'QUINNIPIAC': 'QUIN',
    'EAST CAROLINA': 'ECU',
    'FLORIDA ATLANTIC': 'FAU',
    'WICHITA STATE': 'WICH',
    'TULSA': 'TLSA',
    'NORTH TEXAS': 'UNT',
    'INCARNATE WORD': 'IW',
    'TEXAS A&M CORPUS CHRISTI': 'AMCC',
    'BETHUNE COOKMAN': 'COOK',
    'BETHUNE-COOKMAN': 'COOK',
    'ALABAMA A&M': 'AAMU',
    'NEW ORLEANS': 'UNO',
    'TEXAS A&M COMMERCE': 'TAMC',
    'MCNEESE': 'MCNS',
    'MCNEESE STATE': 'MCNS',
    'GRAMBLING': 'GRAM',
    'ALCORN STATE': 'ALCN',
    'SOUTHERN': 'SOU',
    'JACKSON STATE': 'JKST',
    'WEBER STATE': 'WEB',
    'SACRAMENTO STATE': 'SAC',
    'SOUTH ALABAMA': 'USA',
    'SANTA CLARA': 'SCU',
    'LOYOLA MARYMOUNT': 'LMU',
    'UCF': 'UCF',
    'CENTRAL FLORIDA': 'UCF',
    'BUTLER': 'BUT',
    'VALPARAISO': 'VALP',
    'BRADLEY': 'BRAD',
    'EVANSVILLE': 'EVAN',
    'LOYOLA CHICAGO': 'LCHI',
    'ST. JOHN\'S': 'SJU',
    "ST. JOHN'S": 'SJU',
    'ST JOHN\'S': 'SJU',
    "ST JOHN'S": 'SJU',
    'ST. JOHNS': 'SJU',
    'ST JOHNS': 'SJU',
    'UIC': 'UIC',
    'ILLINOIS-CHICAGO': 'UIC',
    'ILLINOIS CHICAGO': 'UIC',
    'MURRAY STATE': 'MURR',
    'SIU EDWARDSVILLE': 'SIUE',
    'LINDENWOOD': 'LINW',
    'PITTSBURGH': 'PITT',
    'VIRGINIA': 'UVA',
    'AIR FORCE': 'AFA',
    'GRAND CANYON': 'GC',
    'LITTLE ROCK': 'UALR',
    'ARKANSAS-LITTLE ROCK': 'UALR',
    'ARKANSAS LITTLE ROCK': 'UALR',
    'TENNESSEE-MARTIN': 'UTM',
    'TENNESSEE MARTIN': 'UTM',
    'UT MARTIN': 'UTM',
    'SAINT LOUIS': 'SLU',
    'ST. LOUIS': 'SLU',
    'ST LOUIS': 'SLU',
    'DAVIDSON': 'DAV',
    'UCLA': 'UCLA',
    'UNLV': 'UNLV',
    'NEVADA-LAS VEGAS': 'UNLV',
    'NEVADA LAS VEGAS': 'UNLV',
    'FRESNO STATE': 'FRES',
    'NEVADA': 'NEV',
    'BOISE STATE': 'BSU',
    'DRAKE': 'DRKE',
    'BELMONT': 'BEL',
    'KENTUCKY': 'UK',
    'CONNECTICUT': 'CONN',
    'UCONN': 'CONN',
    'TENNESSEE': 'TENN',
    'AUBURN': 'AUB',
    'ALABAMA': 'ALA',
    'ARKANSAS': 'ARK',
    'CLEMSON': 'CLEM',
    'MIAMI': 'MIA',
    'NOTRE DAME': 'ND',
    'PURDUE': 'PUR',
    'WISCONSIN': 'WIS',
    'MARYLAND-EASTERN SHORE': 'UMES',
    'MARYLAND EASTERN SHORE': 'UMES',
    'MARYLAND': 'MD',
    'RUTGERS': 'RUTG',
    'NEBRASKA': 'NEB',
    'MINNESOTA': 'MINN',
    'CREIGHTON': 'CREI',
    'VILLANOVA': 'VILL',
    'PROVIDENCE': 'PROV',
    'GONZAGA': 'GONZ',
    'SAINT MARY\'S': 'SMC',
    "ST. MARY'S": 'SMC',
    'BYU': 'BYU',
    'HOUSTON': 'HOU',
    'MEMPHIS': 'MEM',
    'CINCINNATI': 'CIN',
    'TEMPLE': 'TEM',
    'UAB': 'UAB',
}

# Grok's list (normalized to uppercase)
grok_mappings = {
    'ABILENE CHRISTIAN': 'ACU',
    'AIR FORCE': 'AFA',
    'AKRON': 'AKR',
    'ALABAMA': 'ALA',
    'ALABAMA A&M': 'AAMU',
    'ALABAMA STATE': 'ALST',
    'ALBANY': 'ALB',
    'ALCORN STATE': 'ALCN',
    'AMERICAN': 'AMER',
    'APPALACHIAN STATE': 'APP',
    'ARIZONA': 'ARIZ',
    'ARIZONA STATE': 'ASU',
    'ARKANSAS': 'ARK',
    'ARKANSAS - PINE BLUFF': 'UAPB',
    'ARKANSAS STATE': 'ARST',
    'ARMY': 'ARMY',
    'AUBURN': 'AUB',
    'AUSTIN PEAY': 'APSU',
    'BALL STATE': 'BALL',
    'BAYLOR': 'BAY',
    'BELLARMINE': 'BELL',
    'BELMONT': 'BEL',
    'BETHUNE-COOKMAN': 'BCU',
    'BINGHAMTON': 'BING',
    'BOISE STATE': 'BSU',
    'BOSTON COLLEGE': 'BC',
    'BOSTON UNIVERSITY': 'BU',
    'BOWLING GREEN': 'BGSU',
    'BRADLEY': 'BRAD',
    'BROWN': 'BRWN',
    'BRYANT': 'BRY',
    'BUCKNELL': 'BUCK',
    'BUFFALO': 'BUFF',
    'BUTLER': 'BUT',
    'BYU': 'BYU',
    'CAL POLY': 'CP',
    'CALIFORNIA': 'CAL',
    'CALIFORNIA BAPTIST': 'CBU',
    'CAMPBELL': 'CAM',
    'CANISIUS': 'CAN',
    'CENTRAL ARKANSAS': 'CARK',
    'CENTRAL CONNECTICUT': 'CCSU',
    'CENTRAL MICHIGAN': 'CMU',
    'CHARLESTON': 'COFC',
    'CHARLESTON SOUTHERN': 'CHSO',
    'CHARLOTTE': 'CLT',
    'CHATTANOOGA': 'UTC',
    'CHICAGO STATE': 'CHST',
    'CINCINNATI': 'CIN',
    'CITADEL': 'CIT',
    'CLEMSON': 'CLEM',
    'CLEVELAND STATE': 'CLEV',
    'COASTAL CAROLINA': 'CCU',
    'COLGATE': 'COLG',
    'COLORADO': 'COLO',
    'COLORADO STATE': 'CSU',
    'COLUMBIA': 'COLU',
    'CONNECTICUT': 'CONN',
    'COPPIN STATE': 'COPP',
    'CORNELL': 'COR',
    'CREIGHTON': 'CREI',
    'CSU BAKERSFIELD': 'CSUB',
    'CSU FULLERTON': 'CSUF',
    'CSU NORTHRIDGE': 'CSUN',
    'DARTMOUTH': 'DART',
    'DAVIDSON': 'DAV',
    'DAYTON': 'DAY',
    'DELAWARE': 'DEL',
    'DELAWARE STATE': 'DSU',
    'DENVER': 'DEN',
    'DEPAUL': 'DEP',
    'DETROIT MERCY': 'DETM',
    'DRAKE': 'DRKE',
    'DREXEL': 'DREX',
    'DUKE': 'DUKE',
    'DUQUESNE': 'DUQ',
    'EAST CAROLINA': 'ECU',
    'EAST TENNESSEE STATE': 'ETSU',
    'EASTERN ILLINOIS': 'EIU',
    'EASTERN KENTUCKY': 'EKU',
    'EASTERN MICHIGAN': 'EMU',
    'EASTERN WASHINGTON': 'EWU',
    'ELON': 'ELON',
    'EVANSVILLE': 'EVAN',
    'FAIRFIELD': 'FAIR',
    'FAIRLEIGH DICKINSON': 'FDU',
    'FLORIDA': 'FLA',
    'FLORIDA A&M': 'FAMU',
    'FLORIDA ATLANTIC': 'FAU',
    'FLORIDA GULF COAST': 'FGCU',
    'FLORIDA INTERNATIONAL': 'FIU',
    'FLORIDA STATE': 'FSU',
    'FORDHAM': 'FOR',
    'FRESNO STATE': 'FRES',
    'FURMAN': 'FUR',
    'GARDNER-WEBB': 'GWEB',
    'GEORGE MASON': 'GMU',
    'GEORGE WASHINGTON': 'GW',
    'GEORGETOWN': 'GTWN',
    'GEORGIA': 'UGA',
    'GEORGIA SOUTHERN': 'GASO',
    'GEORGIA STATE': 'GAST',
    'GEORGIA TECH': 'GT',
    'GONZAGA': 'GONZ',
    'GRAMBLING': 'GRAM',
    'GRAND CANYON': 'GC',
    'GREEN BAY': 'GB',
    'HAMPTON': 'HAMP',
    'HARVARD': 'HARV',
    'HAWAII': 'HAW',
    'HIGH POINT': 'HPU',
    'HOFSTRA': 'HOF',
    'HOLY CROSS': 'HC',
    'HOUSTON': 'HOU',
    'HOUSTON CHRISTIAN': 'HCU',
    'HOWARD': 'HOW',
    'IDAHO': 'IDHO',
    'IDAHO STATE': 'IDST',
    'ILLINOIS': 'ILL',
    'ILLINOIS STATE': 'ILST',
    'INCARNATE WORD': 'UIW',
    'INDIANA': 'IU',
    'INDIANA STATE': 'INST',
    'IONA': 'IONA',
    'IOWA': 'IOWA',
    'IOWA STATE': 'ISU',
    'IU INDY': 'IUIN',
    'JACKSON STATE': 'JKST',
    'JACKSONVILLE': 'JAX',
    'JACKSONVILLE STATE': 'JVST',
    'JAMES MADISON': 'JMU',
    'KANSAS': 'KU',
    'KANSAS CITY': 'KC',
    'KANSAS STATE': 'KSU',
    'KENNESAW STATE': 'KENN',
    'KENT STATE': 'KENT',
    'KENTUCKY': 'UK',
    'LA SALLE': 'LAS',
    'LAFAYETTE': 'LAF',
    'LAMAR': 'LAM',
    'LE MOYNE': 'LEM',
    'LEHIGH': 'LEH',
    'LIBERTY': 'LIB',
    'LINDENWOOD': 'LINW',
    'LIPSCOMB': 'LIP',
    'LITTLE ROCK': 'UALR',
    'LIU': 'LIU',
    'LONG BEACH STATE': 'LBSU',
    'LONGWOOD': 'LONG',
    'LOUISIANA': 'UL',
    'LOUISIANA - MONROE': 'ULM',
    'LOUISIANA TECH': 'LT',
    'LOUISVILLE': 'LOU',
    'LOYOLA CHICAGO': 'LCHI',
    'LOYOLA MARYLAND': 'L-MD',
    'LOYOLA MARYMOUNT': 'LMU',
    'LSU': 'LSU',
    'MAINE': 'ME',
    'MANHATTAN': 'MAN',
    'MARIST': 'MRST',
    'MARQUETTE': 'MARQ',
    'MARSHALL': 'MRSH',
    'MARYLAND': 'MD',
    'MARYLAND - EASTERN SHORE': 'UMES',
    'MASSACHUSETTS': 'MASS',
    'MCNEESE': 'MCN',
    'MEMPHIS': 'MEM',
    'MERCER': 'MER',
    'MERCYHURST': 'MERC',
    'MERRIMACK': 'MRMK',
    'MIAMI': 'MIA',
    'MIAMI OF OHIO': 'M-OH',
    'MICHIGAN': 'MICH',
    'MICHIGAN STATE': 'MSU',
    'MIDDLE TENNESSEE': 'MTSU',
    'MILWAUKEE': 'MILW',
    'MINNESOTA': 'MINN',
    'MISSISSIPPI STATE': 'MSST',
    'MISSISSIPPI VALLEY STATE': 'MVSU',
    'MISSOURI': 'MIZ',
    'MISSOURI STATE': 'MOST',
    'MONMOUTH': 'MONM',
    'MONTANA': 'MONT',
    'MONTANA STATE': 'MTST',
    'MOREHEAD STATE': 'MORE',
    'MORGAN STATE': 'MORG',
    'MOUNT ST. MARY\'S': 'MSM',
    'MURRAY STATE': 'MURR',
    'NAVY': 'NAVY',
    'NC STATE': 'NCSU',
    'NEBRASKA': 'NEB',
    'NEVADA': 'NEV',
    'NEW HAMPSHIRE': 'UNH',
    'NEW MEXICO': 'UNM',
    'NEW MEXICO STATE': 'NMSU',
    'NEW ORLEANS': 'UNO',
    'NIAGARA': 'NIAG',
    'NICHOLLS': 'NICH',
    'NJIT': 'NJIT',
    'NORFOLK STATE': 'NORF',
    'NORTH ALABAMA': 'UNA',
    'NORTH CAROLINA': 'UNC',
    'NORTH CAROLINA A&T': 'NCAT',
    'NORTH CAROLINA CENTRAL': 'NCCU',
    'NORTH DAKOTA': 'UND',
    'NORTH DAKOTA STATE': 'NDSU',
    'NORTH FLORIDA': 'UNF',
    'NORTH TEXAS': 'UNT',
    'NORTHEASTERN': 'NE',
    'NORTHERN ARIZONA': 'NAU',
    'NORTHERN COLORADO': 'UNCO',
    'NORTHERN ILLINOIS': 'NIU',
    'NORTHERN IOWA': 'UNI',
    'NORTHERN KENTUCKY': 'NKU',
    'NORTHWESTERN': 'NU',
    'NORTHWESTERN STATE': 'NWST',
    'NOTRE DAME': 'ND',
    'OAKLAND': 'OAK',
    'OHIO': 'OHIO',
    'OHIO STATE': 'OSU',
    'OKLAHOMA': 'OU',
    'OKLAHOMA STATE': 'OKST',
    'OLD DOMINION': 'ODU',
    'OLE MISS': 'MISS',
    'OMAHA': 'OMA',
    'ORAL ROBERTS': 'ORU',
    'OREGON': 'ORE',
    'OREGON STATE': 'ORST',
    'PACIFIC': 'PAC',
    'PENN STATE': 'PSU',
    'PENNSYLVANIA': 'PENN',
    'PEPPERDINE': 'PEPP',
    'PITTSBURGH': 'PITT',
    'PORTLAND': 'PORT',
    'PORTLAND STATE': 'PRST',
    'PRAIRIE VIEW A&M': 'PV',
    'PRESBYTERIAN': 'PRES',
    'PRINCETON': 'PRIN',
    'PROVIDENCE': 'PROV',
    'PURDUE': 'PUR',
    'PURDUE FORT WAYNE': 'PFW',
    'QUEENS': 'QUOC',
    'QUINNIPIAC': 'QUIN',
    'RADFORD': 'RAD',
    'RHODE ISLAND': 'URI',
    'RICE': 'RICE',
    'RICHMOND': 'RICH',
    'RIDER': 'RID',
    'ROBERT MORRIS': 'RMU',
    'RUTGERS': 'RUTG',
    'SACRED HEART': 'SHU',
    'SACRAMENTO STATE': 'SAC',
    'SAINT LOUIS': 'SLU',
    'SAM HOUSTON': 'SHSU',
    'SAMFORD': 'SAM',
    'SAN DIEGO': 'USD',
    'SAN DIEGO STATE': 'SDSU',
    'SAN FRANCISCO': 'SF',
    'SAN JOSE STATE': 'SJSU',
    'SANTA CLARA': 'SCU',
    'SEATTLE': 'SEA',
    'SETON HALL': 'HALL',
    'SIENA': 'SIE',
    'SIU EDWARDSVILLE': 'SIUE',
    'SMU': 'SMU',
    'SOUTH ALABAMA': 'USA',
    'SOUTH CAROLINA': 'SC',
    'SOUTH CAROLINA STATE': 'SCST',
    'SOUTH DAKOTA': 'SDAK',
    'SOUTH DAKOTA STATE': 'SDST',
    'SOUTH FLORIDA': 'USF',
    'SOUTHEAST MISSOURI STATE': 'SEMO',
    'SOUTHEASTERN LOUISIANA': 'SELA',
    'SOUTHERN': 'SOU',
    'SOUTHERN ILLINOIS': 'SIU',
    'SOUTHERN INDIANA': 'USI',
    'SOUTHERN MISS': 'USM',
    'SOUTHERN UTAH': 'SUU',
    'ST. BONAVENTURE': 'SBU',
    'ST. FRANCIS': 'SFPA',
    'ST. JOHN\'S': 'SJU',
    'ST. JOSEPH\'S': 'JOES',
    'ST. MARY\'S': 'SMC',
    'ST. PETER\'S': 'SPU',
    'ST. THOMAS': 'STMN',
    'STANFORD': 'STAN',
    'STEPHEN F. AUSTIN': 'SFA',
    'STETSON': 'STET',
    'STONEHILL': 'STO',
    'STONY BROOK': 'STBK',
    'SYRACUSE': 'SYR',
    'TARLETON': 'TAR',
    'TCU': 'TCU',
    'TEMPLE': 'TEM',
    'TENNESSEE': 'TENN',
    'TENNESSEE - MARTIN': 'UTM',
    'TENNESSEE STATE': 'TNST',
    'TENNESSEE TECH': 'TNTC',
    'TEXAS': 'TEX',
    'TEXAS A&M': 'TA&M',
    'TEXAS A&M-COMMERCE': 'TAMC',
    'TEXAS A&M - CORPUS CHRISTI': 'AMCC',
    'TEXAS - ARLINGTON': 'UTA',
    'TEXAS SOUTHERN': 'TXSO',
    'TEXAS STATE': 'TXST',
    'TEXAS TECH': 'TTU',
    'THE CITADEL': 'CIT',
    'TOLEDO': 'TOL',
    'TOWSON': 'TOW',
    'TROY': 'TROY',
    'TULANE': 'TULN',
    'TULSA': 'TLSA',
    'UAB': 'UAB',
    'UC DAVIS': 'UCD',
    'UC IRVINE': 'UCI',
    'UC RIVERSIDE': 'UCR',
    'UC SAN DIEGO': 'UCSD',
    'UC SANTA BARBARA': 'UCSB',
    'UCF': 'UCF',
    'UCLA': 'UCLA',
    'UIC': 'UIC',
    'UMBC': 'UMBC',
    'UMASS LOWELL': 'UML',
    'UNC ASHEVILLE': 'UNCA',
    'UNC GREENSBORO': 'UNCG',
    'UNC WILMINGTON': 'UNCW',
    'UNLV': 'UNLV',
    'USC': 'USC',
    'USC UPSTATE': 'UPST',
    'UT RIO GRANDE VALLEY': 'RGV',
    'UTAH': 'UTAH',
    'UTAH STATE': 'USU',
    'UTAH TECH': 'UTU',
    'UTAH VALLEY': 'UVU',
    'VALPARAISO': 'VALP',
    'VANDERBILT': 'VAN',
    'VCU': 'VCU',
    'VERMONT': 'UVM',
    'VILLANOVA': 'VILL',
    'VIRGINIA': 'UVA',
    'VIRGINIA TECH': 'VT',
    'VMI': 'VMI',
    'WAGNER': 'WAG',
    'WAKE FOREST': 'WAKE',
    'WASHINGTON': 'WASH',
    'WASHINGTON STATE': 'WSU',
    'WEBER STATE': 'WEB',
    'WEST GEORGIA': 'WGA',
    'WEST VIRGINIA': 'WVU',
    'WESTERN CAROLINA': 'WCU',
    'WESTERN ILLINOIS': 'WIU',
    'WESTERN KENTUCKY': 'WKU',
    'WESTERN MICHIGAN': 'WMU',
    'WICHITA STATE': 'WICH',
    'WILLIAM & MARY': 'W&M',
    'WINTHROP': 'WIN',
    'WISCONSIN': 'WIS',
    'WOFFORD': 'WOF',
    'WRIGHT STATE': 'WRST',
    'WYOMING': 'WYO',
    'XAVIER': 'XAV',
    'YALE': 'YALE',
    'YOUNGSTOWN STATE': 'YSU',
}

# Normalize team names for comparison (remove variations)
def normalize_team_name(name):
    name = name.upper()
    # Handle common variations
    name = name.replace('ST.', 'ST')
    name = name.replace('ST ', 'ST ')
    name = name.replace("'S", '')
    name = name.replace("'", '')
    name = name.replace('-', ' ')
    name = name.replace(' & ', ' ')
    name = name.replace(' AND ', ' ')
    return name.strip()

# Compare
conflicts = []
matches = []
missing_in_ours = []
missing_in_grok = []

# Check teams we have
for our_team, our_code in our_mappings.items():
    our_norm = normalize_team_name(our_team)
    found_match = False
    
    for grok_team, grok_code in grok_mappings.items():
        grok_norm = normalize_team_name(grok_team)
        if our_norm == grok_norm or our_team.upper() in grok_team.upper() or grok_team.upper() in our_team.upper():
            found_match = True
            if our_code == grok_code:
                matches.append((our_team, our_code))
            else:
                conflicts.append((our_team, our_code, grok_team, grok_code))
            break
    
    if not found_match:
        missing_in_grok.append((our_team, our_code))

# Check teams Grok has that we don't
for grok_team, grok_code in grok_mappings.items():
    grok_norm = normalize_team_name(grok_team)
    found_match = False
    
    for our_team, our_code in our_mappings.items():
        our_norm = normalize_team_name(our_team)
        if grok_norm == our_norm or our_team.upper() in grok_team.upper() or grok_team.upper() in our_team.upper():
            found_match = True
            break
    
    if not found_match:
        missing_in_ours.append((grok_team, grok_code))

print("=" * 80)
print("MAPPING COMPARISON RESULTS")
print("=" * 80)
print(f"\n[OK] MATCHES (same code): {len(matches)}")
print(f"[!] CONFLICTS (different codes): {len(conflicts)}")
print(f"[+] MISSING IN OURS (should add): {len(missing_in_ours)}")
print(f"[-] MISSING IN GROK (we have, they don't): {len(missing_in_grok)}")

if conflicts:
    print("\n" + "=" * 80)
    print("[!] CONFLICTS - DO NOT CHANGE OURS (trust our verified mappings):")
    print("=" * 80)
    for our_team, our_code, grok_team, grok_code in conflicts:
        print(f"  OUR: {our_team:40} -> {our_code:6} | GROK: {grok_team:40} -> {grok_code:6}")

if missing_in_ours:
    print("\n" + "=" * 80)
    print("[+] TEAMS TO ADD (from Grok's list):")
    print("=" * 80)
    for team, code in sorted(missing_in_ours):
        print(f"  {team:40} -> {code}")

if missing_in_grok:
    print("\n" + "=" * 80)
    print("[-] TEAMS WE HAVE THAT GROK DOESN'T (keep ours):")
    print("=" * 80)
    for team, code in sorted(missing_in_grok):
        print(f"  {team:40} -> {code}")

print("\n" + "=" * 80)
print("RECOMMENDATION:")
print("=" * 80)
if conflicts:
    print("[!] DO NOT ADD - There are conflicts. Our verified mappings take precedence.")
    print("   Only add teams from 'missing_in_ours' that don't conflict.")
else:
    print("[OK] SAFE TO ADD - No conflicts found. Can add all missing teams.")
print("=" * 80)
